name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Please check with the latest version'
        stale-pr-message: 'Please update your pull request'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
